---
micronaut:
  application:
    name: server
  server:
    cors:
      enabled: true
      configurations:
        all:
          allowedOrigins:
            - https://k-toriumi.github.io

---
postgres:
  reactive:
    client:
      port: 5432
      database: book_database
#      user: user
#      password: password
#      maxSize: 5
