---
micronaut:
  application:
    name: server

---
postgres:
  reactive:
    client:
      port: 5432
      host: localhost
      database: server
#      user: user
#      password: password
#      maxSize: 5
